export const POKEMON_LIST = 'POKEMON_LIST';
export const GET_POKEMON_LIST = 'GET_POKEMON_LIST';
export const POKEMON_ITEM = 'POKEMON_ITEM';
export const MODAL_TOGGLE = 'MODAL_TOGGLE';
export const MENU_TOGGLE = 'MENU_TOGGLE';
export const SELECT_POKEMON = 'SELECT_POKEMON';